version: '3.6'
services: 
  apix2019-notification-nodejs:
    image: sensedia/apix2019-microservice-notification-nodejs
    container_name: notification
    ports:
      - "49160:8080"
    environment:
      TWILIO_FROM_PHONE: ${TWILIO_FROM_PHONE}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    networks:
      - apix2019
networks:
  apix2019:
    external:
      name: apix2019-infra_apix2019           
